# Generated by Django 4.2.2 on 2023-07-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interest',
            field=models.FloatField(),
        ),
    ]
